\documentclass[10pt]{article}
\usepackage[margin=0.8 in]{geometry}
\usepackage{booktabs}
\usepackage{color}
\usepackage{xcolor, colortbl}
\definecolor{Gray}{gray}{0.85}
\newcolumntype{a}{>{\columncolor{Gray}}c}
\usepackage[utf8]{inputenc} 
\usepackage{longtable}
\usepackage[width=.75\textwidth]{caption}
\addtolength{\topmargin}{-.3in}



<<loaddata, echo=FALSE, message=FALSE>>=
credaTable <- vseRjavePDF[ vseRjavePDF$CRE_SIFRA_CREDA == as.numeric(creda),]
credaTable <- credaTable[order(credaTable$DAT_ROJSTVO, decreasing = TRUE),]
credaTable$DAT_ROJSTVO <- format(credaTable$DAT_ROJSTVO, format='%d.%m.%Y')
credaTable$N <- 1:nrow(credaTable)
credaTable <- credaTable[,c(5,1:4)]

seznamBCreda <- seznamB[seznamB$CRE_SIFRA_CREDA == as.numeric(creda),]
desired_order <- c('MatiPS', 'OcePS','MATI')
seznamBCreda$REL <- factor( as.character(seznamBCreda$REL), levels=desired_order )
seznamBCreda <- seznamBCreda[order(seznamBCreda$ID_IzbranaZival, (seznamBCreda$REL), -seznamBCreda$Datum),]
seznamBCreda <- seznamBCreda[,1:6]

stPrim <- nrow(credaTable)
stSek <- nrow(seznamBCreda)
rejec <- rejci$Rejec[rejci$F4F_CRE_SIFRA_CREDA==creda]

credaTable$Nadomestilo <- ifelse(credaTable$ID_ZIVALI %in% seznamBCreda$ID_IzbranaZival,"DA","NE")
library(Cairo)
@

\begin{document}
\includegraphics{KIS_logotip_SLO_vodoravni_barvni}
\includegraphics[width=2cm,height=1.3cm]{logotip1}
\\

{\raggedleft\LARGE Izbor \v{z}ivali za genotipizacijo v \v{c}redi \textbf{\Sexpr{creda}}:} 
\\
\Large{\Sexpr{rejec}}
\\
\\
\Large{\v{S}tevilo \textbf{izbranih}  \v{z}ivali v  \v{c}redi je \textbf\Sexpr{stPrim}.
\\
\v{S}tevilo \textbf{nadomestnih}  \v{z}ivali v  \v{c}redi je \textbf{\Sexpr{stSek}}.}
\vspace{1cm}
\hrule height 1.5pt
\vspace{0.1cm}


\captionsetup{labelformat=empty}

<<PrimarniSeznam, results='asis', echo=FALSE>>=

# define function that will color blank cells green and not blank cells red
color_cells <- function(df, var){
  out <- (paste0("\\cellcolor[HTML]{ececec}{", df[, var], "}"))
}

# apply coloring function to each column you want
credaTable$ID_ZIVALI <- color_cells(df = credaTable, var= "ID_ZIVALI")
credaTable$ID_ZIVALI <- paste0("\\textbf{", credaTable$ID_ZIVALI, "}")  
strCaption <- paste0("\\Large{\\textbf{\\LARGE{SEZNAM A:}} To je seznam primarnih živali za genotipizacijo.",
                     " Če je katera izmed teh izločena, se izbere nadomestno žival iz seznama B SPODAJ.}","\\vspace{0.5cm}")
                     
library(xtable)
xcredaTable <- xtable(credaTable, digits=2, caption=strCaption)
align(xcredaTable) <- "l|l|c|l|l|l|c" 
   
  
print(xcredaTable, 
tabular.environment="longtable",
floating=F,
      size="Large", #Change size; useful for bigger tables
      include.rownames=F, #Don't print rownames
      include.colnames=FALSE, #We create them ourselves
      booktabs=TRUE,
      caption.placement="top",
       table.placement="h",
      sanitize.text.function=identity,
     # sanitize.text.function = function(x) x,
      hline.after = getOption("xtable.hline.after", c(-1:nrow(credaTable))),
      latex.environments="table",
      add.to.row = list(pos = list(-1, 
                                   nrow(credaTable)),
                        command = c(paste("\\toprule \n","N & Sifra crede & ID Zivali & IME Zivali & Rojstvo & Ima nadomestno zival \\\\\n", 
                        "\\midrule \n"),
                        "\\bottomrule \n")))
                        
@
\captionsetup{labelformat=default}
\vspace{0.1cm}
\hrule height 1.5pt
\vspace{0.5cm}
\captionsetup{labelformat=empty}
<<seznamB, results='asis', echo=FALSE>>=

seznamBCreda$ID_IzbranaZival <- color_cells(df = seznamBCreda, var= "ID_IzbranaZival")
seznamBCreda$ID_NadomestnaZival <-  paste0("\\textbf{", seznamBCreda$ID_NadomestnaZival, "}")  
strCaption1 <- paste0("\\Large{\\textbf{\\LARGE{SEZNAM B:}} To je seznam nadomestnih živali za primere,",
                     " ko je katera žival iz seznama A izločena.}","\\vspace{0.5cm}")

                   
xBTable <- xtable(seznamBCreda, digits=2, caption=strCaption1)
align(xBTable) <- "l|c|l|l|l|l|l"                       
print(xBTable, 
tabular.environment="longtable",
floating=F,
      size="Large", #Change size; useful for bigger tables
      include.rownames=FALSE, #Don't print rownames
      include.colnames=FALSE, #We create them ourselves
       sanitize.text.function = identity,
             caption.placement="top",
                    table.placement="t",
      hline.after = getOption("xtable.hline.after", c(-1:nrow(seznamBCreda))),
      latex.environments="flushleft",
      add.to.row = list(pos = list(-1, 
                                   nrow(seznamBCreda)),
                        command = c(paste("\\toprule \n",
                                          "Creda &  Izbrana Zival &   ID Nadom. Ziv. & IME & Rojstvo & Sorodstvo \\\\\n", "\\midrule \n"), "\\bottomrule \n")))
@
\captionsetup{labelformat=default}


\end{document}