
UTILNAME:=zipfile
PKGNAME:=ruamel.std.zipfile
INSTPKGNAME:=--pkg ruamel.std.zipfile
VERSION:=$(shell python setup.py --version)
REGEN:=/home/bin/ruamel_util_new util ruamel.std.zipfile improvements over the standard zipfile package --skip-hg

include ~/.config/ruamel_util_new/Makefile.inc

clean:	clean_common
#	rm -rf build .tox .cache $(PKGNAME).egg-info/ README.pdf
#	find . -name "*.pyc" -exec rm {} +
